name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Prettier
        run: bun prettier --check .
        continue-on-error: false

      - name: Run ESLint
        run: bun lint
        continue-on-error: false

      - name: Check if PR should be blocked
        if: github.event_name == 'pull_request'
        run: |
          if [[ "${{ job.status }}" == "failure" ]]; then
            echo "The 'Build and Test' step failed. The PR will be blocked from merging."
          else
            echo "The 'Build and Test' step passed. The PR can be merged."
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "Build failed. Please check the logs for details."
          # Optionally, send notifications or update PR status